// Generates the primitive color palettes of `projects/ngx-gorilla-ui/styles/tokens.css`.
//
// Each tone gets 12 steps with `light-dark()` values, in the spirit of Radix Colors:
//   1-2 backgrounds, 3-5 subtle backgrounds, 6-8 borders, 9 solid (the brand color, the same in
//   both themes), 10 solid hover, 11 low-contrast text, 12 high-contrast text.
// Plus `--gorilla-<tone>-active` (pressed solid) and `--gorilla-<tone>-contrast` (the text color
// on steps 9, 10 and active: white or near-black).
//
// The script checks WCAG AA contrast for every pair the semantic tokens rely on and fails if one
// does not pass, so the palette can be tuned here and regenerated with `npm run tokens:palette`.
import { readFileSync, writeFileSync } from 'node:fs';

const TOKENS_FILE = new URL('../projects/ngx-gorilla-ui/styles/tokens.css', import.meta.url);
const START = '/* palette:start (generated by scripts/generate-palette.mjs, do not edit) */';
const END = '/* palette:end */';

/** Base (step 9) color of each tone. Brand tones come from the light theme of ngx-monkey-ui. */
const TONES = {
  gray: { solid: null, hue: 235, chroma: 0.012 },
  cyan: { solid: '#40d2ec' },
  violet: { solid: '#967adc' },
  magenta: { solid: '#ff00ff' },
  green: { solid: '#32cd32' },
  amber: { solid: '#ffcc00' },
  red: { solid: '#dc3545' },
  blue: { solid: '#3b82f6' },
};

const LIGHT_L = [0.993, 0.979, 0.955, 0.928, 0.898, 0.862, 0.815, 0.75];
const DARK_L = [0.17, 0.2, 0.24, 0.28, 0.32, 0.37, 0.43, 0.51];
const CHROMA_FACTOR = [0.06, 0.12, 0.22, 0.32, 0.42, 0.52, 0.66, 0.82];
const WHITE = '#ffffff';
const INK = '#0e1214';
const AA = 4.5;

// --- Color math (OKLCH <-> sRGB, WCAG luminance) ---------------------------------------------

const toLinear = (c) => (c <= 0.04045 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4);
const toGamma = (c) => (c <= 0.0031308 ? 12.92 * c : 1.055 * c ** (1 / 2.4) - 0.055);

function hexToRgb(hex) {
  const n = parseInt(hex.slice(1), 16);
  return [(n >> 16) & 255, (n >> 8) & 255, n & 255].map((v) => v / 255);
}

function rgbToHex(rgb) {
  return `#${rgb
    .map((v) =>
      Math.round(Math.min(1, Math.max(0, v)) * 255)
        .toString(16)
        .padStart(2, '0'),
    )
    .join('')}`;
}

function rgbToOklch([r, g, b]) {
  const [lr, lg, lb] = [r, g, b].map(toLinear);
  const l = Math.cbrt(0.4122214708 * lr + 0.5363325363 * lg + 0.0514459929 * lb);
  const m = Math.cbrt(0.2119034982 * lr + 0.6806995451 * lg + 0.1073969566 * lb);
  const s = Math.cbrt(0.0883024619 * lr + 0.2817188376 * lg + 0.6299787005 * lb);
  const L = 0.2104542553 * l + 0.793617785 * m - 0.0040720468 * s;
  const A = 1.9779984951 * l - 2.428592205 * m + 0.4505937099 * s;
  const B = 0.0259040371 * l + 0.7827717662 * m - 0.808675766 * s;
  return [L, Math.hypot(A, B), ((Math.atan2(B, A) * 180) / Math.PI + 360) % 360];
}

function oklchToLinear([L, C, H]) {
  const a = C * Math.cos((H * Math.PI) / 180);
  const b = C * Math.sin((H * Math.PI) / 180);
  const l = (L + 0.3963377774 * a + 0.2158037573 * b) ** 3;
  const m = (L - 0.1055613458 * a - 0.0638541728 * b) ** 3;
  const s = (L - 0.0894841775 * a - 1.291485548 * b) ** 3;
  return [
    4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s,
    -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s,
    -0.0041960863 * l - 0.7034186147 * m + 1.707614701 * s,
  ];
}

/** OKLCH to hex, reducing chroma until the color fits in sRGB. */
function oklchToHex([L, C, H]) {
  let chroma = C;
  for (;;) {
    const linear = oklchToLinear([L, chroma, H]);
    if (linear.every((v) => v >= -1e-4 && v <= 1 + 1e-4) || chroma < 1e-4) {
      return rgbToHex(linear.map(toGamma));
    }
    chroma *= 0.97;
  }
}

function luminance(hex) {
  const [r, g, b] = hexToRgb(hex).map(toLinear);
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
}

function contrast(a, b) {
  const [hi, lo] = [luminance(a), luminance(b)].sort((x, y) => y - x);
  return (hi + 0.05) / (lo + 0.05);
}

// --- Scale generation -------------------------------------------------------------------------

function scale(name, tone) {
  const [baseL, baseC, baseH] = tone.solid
    ? rgbToOklch(hexToRgb(tone.solid))
    : [0.56, tone.chroma, tone.hue];
  const solid = tone.solid ?? oklchToHex([baseL, baseC, baseH]);
  const contrastColor = contrast(solid, WHITE) >= contrast(solid, INK) ? WHITE : INK;
  // Hover moves away from the text color, so its contrast never drops below the solid one.
  const hoverL = baseL + (contrastColor === WHITE ? -0.045 : 0.045);
  const hover = oklchToHex([hoverL, baseC, baseH]);
  const active = oklchToHex([baseL + (contrastColor === WHITE ? -0.09 : 0.09), baseC, baseH]);

  const light = LIGHT_L.map((L, i) => oklchToHex([L, baseC * CHROMA_FACTOR[i], baseH]));
  const dark = DARK_L.map((L, i) => oklchToHex([L, baseC * CHROMA_FACTOR[i], baseH]));

  // Step 11 is text on steps 1-4: darken (light) or lighten (dark) it until it passes AA.
  const textOn = (backgrounds, start, step) => {
    let L = start;
    let hex = oklchToHex([L, baseC * 0.9, baseH]);
    while (backgrounds.some((bg) => contrast(hex, bg) < AA)) {
      L += step;
      hex = oklchToHex([L, baseC * 0.9, baseH]);
    }
    return hex;
  };
  const light11 = textOn(light.slice(0, 4), 0.52, -0.01);
  const dark11 = textOn(dark.slice(0, 4), 0.8, 0.01);
  const light12 = oklchToHex([0.27, baseC * 0.45, baseH]);
  const dark12 = oklchToHex([0.95, baseC * 0.2, baseH]);

  const steps = [
    ...light.map((l, i) => [l, dark[i]]),
    [solid, solid],
    [hover, hover],
    [light11, dark11],
    [light12, dark12],
  ];

  const checks = [
    [`${name}-contrast on ${name}-9`, contrast(contrastColor, solid)],
    [`${name}-contrast on ${name}-10`, contrast(contrastColor, hover)],
    [`${name}-contrast on ${name}-active`, contrast(contrastColor, active)],
    [`${name}-12 on ${name}-1 (light)`, contrast(light12, light[0])],
    [`${name}-12 on ${name}-1 (dark)`, contrast(dark12, dark[0])],
  ];
  for (const failure of checks.filter(([, ratio]) => ratio < AA)) {
    throw new Error(`${failure[0]} has a contrast of ${failure[1].toFixed(2)}, below ${AA}`);
  }

  const lines = steps.map(([l, d], i) =>
    l === d
      ? `    --gorilla-${name}-${i + 1}: ${l};`
      : `    --gorilla-${name}-${i + 1}: light-dark(${l}, ${d});`,
  );
  lines.push(`    --gorilla-${name}-active: ${active};`);
  lines.push(`    --gorilla-${name}-contrast: ${contrastColor};`);
  return lines.join('\n');
}

const block = Object.entries(TONES)
  .map(([name, tone]) => scale(name, tone))
  .join('\n\n');

const css = readFileSync(TOKENS_FILE, 'utf8');
const start = css.indexOf(START);
const end = css.indexOf(END);
if (start === -1 || end === -1) {
  throw new Error(`tokens.css must contain the "${START}" and "${END}" markers`);
}
writeFileSync(
  TOKENS_FILE,
  `${css.slice(0, start + START.length)}\n${block}\n    ${css.slice(end)}`,
);
console.log('Palette written to projects/ngx-gorilla-ui/styles/tokens.css');
